on:
  push:
    paths:
      - "flake.*"

jobs:
  build:
    name: Build the Nix flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build the flake
        run: nix build
      - name: Build the flake
        run: nix flake check
